name: CD_SCOPE Code Quality

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pylint numpy scipy PyQt5 pyqtgraph

      - name: Run Pylint
        run: |
          pylint cd_scope/ --fail-under=7.0
          # --fail-under=7.0 means the CI fails if score < 7/10
